; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt < %s -passes=slsr -S | FileCheck %s

; SLSR models "Base | Index" as "Base + Index" when the operands are disjoint,
; and so does SCEV for `or disjoint`. Because rewriting a candidate drops the
; poison-generating annotations of the instructions it reuses, that equality is
; rewritten into the opcode up front instead of being re-proven later.

declare void @foo(i32)

; Disjointness is provable from the shl, independently of any flag.
define void @known_disjoint_from_shl(i32 %a, i32 %s) {
; CHECK-LABEL: define void @known_disjoint_from_shl(
; CHECK-SAME: i32 [[A:%.*]], i32 [[S:%.*]]) {
; CHECK-NEXT:    [[B:%.*]] = shl i32 [[A]], 4
; CHECK-NEXT:    [[B1:%.*]] = add i32 [[B]], 1
; CHECK-NEXT:    [[MUL1:%.*]] = mul i32 [[B1]], [[S]]
; CHECK-NEXT:    call void @foo(i32 [[MUL1]])
; CHECK-NEXT:    [[MUL2:%.*]] = add i32 [[MUL1]], [[S]]
; CHECK-NEXT:    call void @foo(i32 [[MUL2]])
; CHECK-NEXT:    ret void
;
  %b = shl i32 %a, 4
  %b1 = or disjoint i32 %b, 1
  %mul1 = mul i32 %b1, %s
  call void @foo(i32 %mul1)
  %b2 = add i32 %b, 2
  %mul2 = mul i32 %b2, %s
  call void @foo(i32 %mul2)
  ret void
}

; Same, but the `or` never had the disjoint flag to begin with.
define void @known_disjoint_no_flag(i32 %a, i32 %s) {
; CHECK-LABEL: define void @known_disjoint_no_flag(
; CHECK-SAME: i32 [[A:%.*]], i32 [[S:%.*]]) {
; CHECK-NEXT:    [[B:%.*]] = shl i32 [[A]], 4
; CHECK-NEXT:    [[B1:%.*]] = add i32 [[B]], 1
; CHECK-NEXT:    [[MUL1:%.*]] = mul i32 [[B1]], [[S]]
; CHECK-NEXT:    call void @foo(i32 [[MUL1]])
; CHECK-NEXT:    [[MUL2:%.*]] = add i32 [[MUL1]], [[S]]
; CHECK-NEXT:    call void @foo(i32 [[MUL2]])
; CHECK-NEXT:    ret void
;
  %b = shl i32 %a, 4
  %b1 = or i32 %b, 1
  %mul1 = mul i32 %b1, %s
  call void @foo(i32 %mul1)
  %b2 = add i32 %b, 2
  %mul2 = mul i32 %b2, %s
  call void @foo(i32 %mul2)
  ret void
}

; Nothing establishes disjointness except the flag itself. Rewriting the `or`
; as an `add` is still a refinement: if the operands do overlap the `or` was
; poison, and the `add` refines poison.
define void @disjoint_flag_only(i32 %b, i32 %s) {
; CHECK-LABEL: define void @disjoint_flag_only(
; CHECK-SAME: i32 [[B:%.*]], i32 [[S:%.*]]) {
; CHECK-NEXT:    [[B1:%.*]] = add i32 [[B]], 1
; CHECK-NEXT:    [[MUL1:%.*]] = mul i32 [[B1]], [[S]]
; CHECK-NEXT:    call void @foo(i32 [[MUL1]])
; CHECK-NEXT:    [[MUL2:%.*]] = add i32 [[MUL1]], [[S]]
; CHECK-NEXT:    call void @foo(i32 [[MUL2]])
; CHECK-NEXT:    ret void
;
  %b1 = or disjoint i32 %b, 1
  %mul1 = mul i32 %b1, %s
  call void @foo(i32 %mul1)
  %b2 = add i32 %b, 2
  %mul2 = mul i32 %b2, %s
  call void @foo(i32 %mul2)
  ret void
}

; The operands may overlap and there is no flag, so the `or` is not an add and
; must be left alone.
define void @not_disjoint(i32 %b, i32 %s) {
; CHECK-LABEL: define void @not_disjoint(
; CHECK-SAME: i32 [[B:%.*]], i32 [[S:%.*]]) {
; CHECK-NEXT:    [[B1:%.*]] = or i32 [[B]], 1
; CHECK-NEXT:    [[MUL1:%.*]] = mul i32 [[B1]], [[S]]
; CHECK-NEXT:    call void @foo(i32 [[MUL1]])
; CHECK-NEXT:    [[B2:%.*]] = add i32 [[B]], 2
; CHECK-NEXT:    [[MUL2:%.*]] = mul i32 [[B2]], [[S]]
; CHECK-NEXT:    call void @foo(i32 [[MUL2]])
; CHECK-NEXT:    ret void
;
  %b1 = or i32 %b, 1
  %mul1 = mul i32 %b1, %s
  call void @foo(i32 %mul1)
  %b2 = add i32 %b, 2
  %mul2 = mul i32 %b2, %s
  call void @foo(i32 %mul2)
  ret void
}

; Disjointness rests entirely on the `nneg` flag of %z1, which is dropped when
; %mul1 is reused as a basis. Reusing the `or` after that drop would compute
; %z1 | 128 where SCEV expects %z1 + 128; for %x = 128 the function must still
; return 257, not 129.
define i32 @flag_dependent_disjointness(i8 %x, i32 %s) {
; CHECK-LABEL: define i32 @flag_dependent_disjointness(
; CHECK-SAME: i8 [[X:%.*]], i32 [[S:%.*]]) {
; CHECK-NEXT:    [[Z1:%.*]] = zext i8 [[X]] to i32
; CHECK-NEXT:    [[B1:%.*]] = add i32 [[Z1]], 128
; CHECK-NEXT:    [[MUL1:%.*]] = mul i32 [[B1]], [[S]]
; CHECK-NEXT:    [[MUL2:%.*]] = add i32 [[MUL1]], [[S]]
; CHECK-NEXT:    ret i32 [[MUL2]]
;
  %z1 = zext nneg i8 %x to i32
  %b1 = or disjoint i32 %z1, 128
  %mul1 = mul i32 %b1, %s
  %z2 = zext i8 %x to i32
  %b2 = add i32 %z2, 129
  %mul2 = mul i32 %b2, %s
  ret i32 %mul2
}

; The constant may be on either side.
define void @commuted_constant(i32 %a, i32 %s) {
; CHECK-LABEL: define void @commuted_constant(
; CHECK-SAME: i32 [[A:%.*]], i32 [[S:%.*]]) {
; CHECK-NEXT:    [[B:%.*]] = shl i32 [[A]], 4
; CHECK-NEXT:    [[B1:%.*]] = add i32 1, [[B]]
; CHECK-NEXT:    [[MUL1:%.*]] = mul i32 [[B1]], [[S]]
; CHECK-NEXT:    call void @foo(i32 [[MUL1]])
; CHECK-NEXT:    [[MUL2:%.*]] = add i32 [[MUL1]], [[S]]
; CHECK-NEXT:    call void @foo(i32 [[MUL2]])
; CHECK-NEXT:    ret void
;
  %b = shl i32 %a, 4
  %b1 = or disjoint i32 1, %b
  %mul1 = mul i32 %b1, %s
  call void @foo(i32 %mul1)
  %b2 = add i32 %b, 2
  %mul2 = mul i32 %b2, %s
  call void @foo(i32 %mul2)
  ret void
}

; SLSR only ever splits an `or` with a constant, so a disjoint `or` of two
; variables is left alone.
define void @or_non_constant(i32 %a, i32 %c, i32 %s) {
; CHECK-LABEL: define void @or_non_constant(
; CHECK-SAME: i32 [[A:%.*]], i32 [[C:%.*]], i32 [[S:%.*]]) {
; CHECK-NEXT:    [[B:%.*]] = shl i32 [[A]], 16
; CHECK-NEXT:    [[M:%.*]] = lshr i32 [[C]], 16
; CHECK-NEXT:    [[B1:%.*]] = or disjoint i32 [[B]], [[M]]
; CHECK-NEXT:    [[MUL1:%.*]] = mul i32 [[B1]], [[S]]
; CHECK-NEXT:    call void @foo(i32 [[MUL1]])
; CHECK-NEXT:    ret void
;
  %b = shl i32 %a, 16
  %m = lshr i32 %c, 16
  %b1 = or disjoint i32 %b, %m
  %mul1 = mul i32 %b1, %s
  call void @foo(i32 %mul1)
  ret void
}

; An `or` that no mul consumes is not SLSR's business.
define i32 @or_not_feeding_mul(i32 %a) {
; CHECK-LABEL: define i32 @or_not_feeding_mul(
; CHECK-SAME: i32 [[A:%.*]]) {
; CHECK-NEXT:    [[B:%.*]] = shl i32 [[A]], 4
; CHECK-NEXT:    [[B1:%.*]] = or disjoint i32 [[B]], 1
; CHECK-NEXT:    ret i32 [[B1]]
;
  %b = shl i32 %a, 4
  %b1 = or disjoint i32 %b, 1
  ret i32 %b1
}

; One `or` reaching two muls is converted exactly once.
define void @or_shared_by_two_muls(i32 %a, i32 %s, i32 %t) {
; CHECK-LABEL: define void @or_shared_by_two_muls(
; CHECK-SAME: i32 [[A:%.*]], i32 [[S:%.*]], i32 [[T:%.*]]) {
; CHECK-NEXT:    [[B:%.*]] = shl i32 [[A]], 4
; CHECK-NEXT:    [[B1:%.*]] = add i32 [[B]], 1
; CHECK-NEXT:    [[MUL1:%.*]] = mul i32 [[B1]], [[S]]
; CHECK-NEXT:    [[MUL2:%.*]] = mul i32 [[B1]], [[T]]
; CHECK-NEXT:    call void @foo(i32 [[MUL1]])
; CHECK-NEXT:    call void @foo(i32 [[MUL2]])
; CHECK-NEXT:    ret void
;
  %b = shl i32 %a, 4
  %b1 = or disjoint i32 %b, 1
  %mul1 = mul i32 %b1, %s
  %mul2 = mul i32 %b1, %t
  call void @foo(i32 %mul1)
  call void @foo(i32 %mul2)
  ret void
}

; Both operands of the mul are disjoint ors.
define void @both_mul_operands_are_ors(i32 %p, i32 %q) {
; CHECK-LABEL: define void @both_mul_operands_are_ors(
; CHECK-SAME: i32 [[P:%.*]], i32 [[Q:%.*]]) {
; CHECK-NEXT:    [[B1:%.*]] = add i32 [[P]], 1
; CHECK-NEXT:    [[B2:%.*]] = add i32 [[Q]], 2
; CHECK-NEXT:    [[M:%.*]] = mul i32 [[B1]], [[B2]]
; CHECK-NEXT:    call void @foo(i32 [[M]])
; CHECK-NEXT:    ret void
;
  %b1 = or disjoint i32 %p, 1
  %b2 = or disjoint i32 %q, 2
  %m = mul i32 %b1, %b2
  call void @foo(i32 %m)
  ret void
}

; Only the `or` feeding the mul is converted. %o1 is still a disjoint `or`, so
; canReuseInstruction() continues to reject %mul1 as a basis and %mul2 is not
; strength-reduced. Converting the whole operand graph would unlock this.
define void @chained_disjoint_ors(i32 %a, i32 %s) {
; CHECK-LABEL: define void @chained_disjoint_ors(
; CHECK-SAME: i32 [[A:%.*]], i32 [[S:%.*]]) {
; CHECK-NEXT:    [[B:%.*]] = shl i32 [[A]], 8
; CHECK-NEXT:    [[O1:%.*]] = or disjoint i32 [[B]], 1
; CHECK-NEXT:    [[O2:%.*]] = add i32 [[O1]], 2
; CHECK-NEXT:    [[MUL1:%.*]] = mul i32 [[O2]], [[S]]
; CHECK-NEXT:    call void @foo(i32 [[MUL1]])
; CHECK-NEXT:    [[B2:%.*]] = add i32 [[B]], 4
; CHECK-NEXT:    [[MUL2:%.*]] = mul i32 [[B2]], [[S]]
; CHECK-NEXT:    call void @foo(i32 [[MUL2]])
; CHECK-NEXT:    ret void
;
  %b = shl i32 %a, 8
  %o1 = or disjoint i32 %b, 1
  %o2 = or disjoint i32 %o1, 2
  %mul1 = mul i32 %o2, %s
  call void @foo(i32 %mul1)
  %b2 = add i32 %b, 4
  %mul2 = mul i32 %b2, %s
  call void @foo(i32 %mul2)
  ret void
}

; SLSR only handles integer muls.
define <2 x i32> @vector_or(<2 x i32> %a, <2 x i32> %s) {
; CHECK-LABEL: define <2 x i32> @vector_or(
; CHECK-SAME: <2 x i32> [[A:%.*]], <2 x i32> [[S:%.*]]) {
; CHECK-NEXT:    [[B:%.*]] = shl <2 x i32> [[A]], splat (i32 4)
; CHECK-NEXT:    [[B1:%.*]] = or disjoint <2 x i32> [[B]], splat (i32 1)
; CHECK-NEXT:    [[MUL1:%.*]] = mul <2 x i32> [[B1]], [[S]]
; CHECK-NEXT:    ret <2 x i32> [[MUL1]]
;
  %b = shl <2 x i32> %a, splat (i32 4)
  %b1 = or disjoint <2 x i32> %b, splat (i32 1)
  %mul1 = mul <2 x i32> %b1, %s
  ret <2 x i32> %mul1
}
